version: '3.4'

services:
  app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "9001:80"
      - "9000:443"
      - "9051:5000"
      - "9050:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

    network_mode: bridge
    hostname: adefhelpdesk
    extra_hosts:
      - "localhost:172.17.0.1"
