version: '3.7'

services:
  app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Fitness1000!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/cert.pfx
    ports:
      - "9001:80"
      - "9000:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

    network_mode: bridge
    hostname: adefhelpdesk
    extra_hosts:
      - "localhost:172.17.0.1"
